import { Stack } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/common";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Welcome to the Rick and Morty website</h2>
      <Stack
        direction="row"
        spacing={16}
        justifyContent="center"
        sx={{ mt: 64 }}
      >
        <Button variant="secondary" size="medium">
          <Link href="/characters">Go to characters list</Link>
        </Button>
        <Button variant="secondary" size="medium">
          <Link href="/locations">Go to locations list</Link>
        </Button>
      </Stack>
    </div>
  );
};

export async function getStaticProps() {
  return { props: {}, revalidate: 10 };
}

export default Home;
